### ISSUE TITLE
5.1?

### ISSUE THREAD

**Issue by imtrobin** [rionix/ShapesVisualizer#2] opened 2023-01-04 11:38 UTC
Can't compile in 5.1

**Comment by maltsevda** [comment] 2023-01-05 07:29
I'm waiting for the release of the new engine version 5.1.1, which will fix the bug with the building for Android devices.

https://forums.unrealengine.com/t/5-1-missing-precompiled-manifest-error-when-building-code-plugin-for-android/691983

Here's what the Epic's developer says:

> Hi, thanks for the report, and the workarounds posted. We’ll make sure we get this fixed for 5.1.1 and we will also post the UBT/UAT code fix once we have it.

**Comment by imtrobin** [comment] 2023-01-05 08:23
ok thanks. I fixed the header to compile for 5.1, but my existing project willl crash

![image](https://user-images.githubusercontent.com/531606/210734254-364625f3-7c3c-47f2-b41c-0878da6ee60b.png)

**Comment by maltsevda** [comment] 2023-01-06 10:14
You don't need to make any fixes in the plugin to work in 5.1. Just create a Plugins folder in your project and copy the repository folder to it. I can't build this plugin for the Android platform, that's why I'm not publishing it. The only thing, make sure that ShapesVisualizer.uplugin file has engine version 5.1.0, not 4.27.0.

**Comment by imtrobin** [comment] 2023-01-07 04:01
I did that. One of the header didn't compile, I just added that.

**Comment by maltsevda** [comment] 2023-01-07 08:15
This is very strange because everything compiles fine on my engine 5.1 without any fixes. And everything works without errors.

I can try to figure out the problem if I know exactly what has been changed. And I need all the information about the crash, in the screenshot the part of the callstack with the crash location (GetDynamicMeshElements function) is cropped.

**Comment by imtrobin** [comment] 2023-01-10 05:48
![image](https://user-images.githubusercontent.com/531606/211471269-cbeee161-6699-4115-9d6d-771f09062098.png)

The  only change is add #include "DynamicMeshBuilder.h" to build for 5.1

**Comment by maltsevda** [comment] 2023-01-17 14:11
You are using an old code. This bug has already been fixed in this repository:
```cpp
FMaterialRenderProxy* const MeshMaterial = ParentMaterial
                ? new FColoredMaterialRenderProxy(ParentMaterial, Color)
                : nullptr;
```
Just pull and compile the code from this repository. And don't change anything. And all be fine. :)

**Comment by imtrobin** [comment] 2023-01-19 01:46
I see. I was using the one from the marketplace

**Comment by imtrobin** [comment] 2023-01-19 02:34
1.2 branch, the plugin version is still listed as 1.0

**Comment by maltsevda** [comment] 2023-01-19 09:51
If the problem is solved, I'm closing this thread?

**Closed as completed** 2023-01-29 09:23 UTC
